// Auto-generated artwork data - 2025-09-24T15:47:53.863Z
// This file is automatically generated from images in src/lib/assets/images/
// To regenerate, run: npm run generate:artwork-data

import type { Artwork } from '$lib/types/artwork';

// Import all images with enhanced processing
import acrilico1 from '$lib/assets/images/acrilico-1.webp?enhanced';
import acrilico1Zoom1 from '$lib/assets/images/acrilico-1-zoom-1.webp?enhanced';
import albor from '$lib/assets/images/albor.webp?enhanced';
import alborZoom1 from '$lib/assets/images/albor-zoom-1.webp?enhanced';
import alconCollage from '$lib/assets/images/alcon-collage.webp?enhanced';
import apunteAbstracto1 from '$lib/assets/images/apunte-abstracto-1.webp?enhanced';
import apunteAbstracto2 from '$lib/assets/images/apunte-abstracto-2.webp?enhanced';
import apunteAbstracto3 from '$lib/assets/images/apunte-abstracto-3.webp?enhanced';
import apunteBaezaAcuerela from '$lib/assets/images/apunte-baeza-acuerela.webp?enhanced';
import apuntePaisajeAcrilico from '$lib/assets/images/apunte-paisaje-acrilico.webp?enhanced';
import apuntePaisajeAcuarela1 from '$lib/assets/images/apunte-paisaje-acuarela-1.webp?enhanced';
import apuntePaisajeAcuarela3 from '$lib/assets/images/apunte-paisaje-acuarela-3.webp?enhanced';
import apuntePaisajeAcuarela4 from '$lib/assets/images/apunte-paisaje-acuarela-4.webp?enhanced';
import apuntePaisajeAcuarela5 from '$lib/assets/images/apunte-paisaje-acuarela-5.webp?enhanced';
import apuntePaisajeCollage1 from '$lib/assets/images/apunte-paisaje-collage-1.webp?enhanced';
import apuntePaisajeCollage2 from '$lib/assets/images/apunte-paisaje-collage-2.webp?enhanced';
import belong from '$lib/assets/images/belong.webp?enhanced';
import celebesSea from '$lib/assets/images/celebes-sea.webp?enhanced';
import celebesSeaZoom1 from '$lib/assets/images/celebes-sea-zoom-1.webp?enhanced';
import celebesSeaZoom2 from '$lib/assets/images/celebes-sea-zoom-2.webp?enhanced';
import dama from '$lib/assets/images/dama.webp?enhanced';
import estudioRetrato1 from '$lib/assets/images/estudio-retrato-1.webp?enhanced';
import estudioRetrato1Zoom1 from '$lib/assets/images/estudio-retrato-1-zoom-1.webp?enhanced';
import estudioRetrato1Zoom2 from '$lib/assets/images/estudio-retrato-1-zoom-2.webp?enhanced';
import estudioRetrato2 from '$lib/assets/images/estudio-retrato-2.webp?enhanced';
import estudioRetrato2Zoom1 from '$lib/assets/images/estudio-retrato-2-zoom-1.webp?enhanced';
import grafitoCatedral from '$lib/assets/images/grafito-catedral.webp?enhanced';
import hombreConBarba from '$lib/assets/images/hombre-con-barba.webp?enhanced';
import lechera from '$lib/assets/images/lechera.webp?enhanced';
import lilith from '$lib/assets/images/lilith.webp?enhanced';
import lilithZoom1 from '$lib/assets/images/lilith-zoom-1.webp?enhanced';
import nuevosAcercamientos from '$lib/assets/images/nuevos-acercamientos.webp?enhanced';
import perpetuidad from '$lib/assets/images/perpetuidad.webp?enhanced';
import retratoAnciano from '$lib/assets/images/retrato-anciano.webp?enhanced';
import retratoDelFayum from '$lib/assets/images/retrato-del-fayum.webp?enhanced';
import retratoSanguina from '$lib/assets/images/retrato-sanguina.webp?enhanced';
import summary from '$lib/assets/images/summary.webp?enhanced';
import theJoke from '$lib/assets/images/the-joke.webp?enhanced';
import theRockero from '$lib/assets/images/the-rockero.webp?enhanced';
import timeAfterTime from '$lib/assets/images/time-after-time.webp?enhanced';
import tragaluz from '$lib/assets/images/tragaluz.webp?enhanced';
import xauen from '$lib/assets/images/xauen.webp?enhanced';

export const artworkData: Artwork[] = [
	{
		id: 'acrilico-1',
		title: 'Acrilico 1',
		description:
			'This piece captures a moment in time with remarkable sensitivity and artistic insight.',
		price: 3431,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: acrilico1
			},
			{
				name: 'zoom-1',
				picture: acrilico1Zoom1
			}
		],
		year: 2017,
		dimensions: {
			width: 30,
			height: 26,
			unit: 'cm'
		},
		category: 'Painting',
		isAvailable: true
	},
	{
		id: 'albor',
		title: 'Albor',
		description:
			'This piece demonstrates exceptional skill in composition and color theory, creating a visually striking experience.',
		price: 1851,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: albor
			},
			{
				name: 'zoom-1',
				picture: alborZoom1
			}
		],
		year: 2015,
		dimensions: {
			width: 56,
			height: 112,
			unit: 'cm'
		},
		category: 'Digital Art',
		isAvailable: true
	},
	{
		id: 'alcon-collage',
		title: 'Alcon Collage',
		description:
			'A beautiful piece that harmonizes form and content, creating a lasting impression on the viewer.',
		price: 1950,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: alconCollage
			}
		],
		year: 2024,
		dimensions: {
			width: 55,
			height: 52,
			unit: 'cm'
		},
		category: 'Collage',
		isAvailable: true
	},
	{
		id: 'apunte-abstracto-1',
		title: 'Apunte Abstracto 1',
		description:
			'This work demonstrates innovative approaches to traditional artistic concepts, resulting in a fresh perspective.',
		price: 4431,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: apunteAbstracto1
			}
		],
		year: 2016,
		dimensions: {
			width: 59,
			height: 72,
			unit: 'cm'
		},
		category: 'Contemporary',
		isAvailable: true
	},
	{
		id: 'apunte-abstracto-2',
		title: 'Apunte Abstracto 2',
		description:
			'An evocative work that invites contemplation and reflection through its subtle nuances and artistic expression.',
		price: 1581,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: apunteAbstracto2
			}
		],
		year: 2023,
		dimensions: {
			width: 60,
			height: 55,
			unit: 'cm'
		},
		category: 'Portrait',
		isAvailable: true
	},
	{
		id: 'apunte-abstracto-3',
		title: 'Apunte Abstracto 3',
		description:
			"This artwork showcases the artist's mastery of technique while conveying deep emotional resonance.",
		price: 831,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: apunteAbstracto3
			}
		],
		year: 2021,
		dimensions: {
			width: 68,
			height: 77,
			unit: 'cm'
		},
		category: 'Contemporary',
		isAvailable: true
	},
	{
		id: 'apunte-baeza-acuerela',
		title: 'Apunte Baeza Acuerela',
		description:
			'This artwork represents a unique perspective on contemporary themes, blending traditional techniques with modern sensibilities.',
		price: 157,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: apunteBaezaAcuerela
			}
		],
		year: 2015,
		dimensions: {
			width: 60,
			height: 71,
			unit: 'cm'
		},
		category: 'Portrait',
		isAvailable: true
	},
	{
		id: 'apunte-paisaje-acrilico',
		title: 'Apunte Paisaje Acrilico',
		description:
			'A beautiful piece that harmonizes form and content, creating a lasting impression on the viewer.',
		price: 2449,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: apuntePaisajeAcrilico
			}
		],
		year: 2023,
		dimensions: {
			width: 93,
			height: 118,
			unit: 'cm'
		},
		category: 'Photography',
		isAvailable: true
	},
	{
		id: 'apunte-paisaje-acuarela-1',
		title: 'Apunte Paisaje Acuarela 1',
		description:
			'This work demonstrates innovative approaches to traditional artistic concepts, resulting in a fresh perspective.',
		price: 496,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: apuntePaisajeAcuarela1
			}
		],
		year: 2019,
		dimensions: {
			width: 40,
			height: 34,
			unit: 'cm'
		},
		category: 'Mixed Media',
		isAvailable: true
	},
	{
		id: 'apunte-paisaje-acuarela-3',
		title: 'Apunte Paisaje Acuarela 3',
		description:
			'This artwork represents a unique perspective on contemporary themes, blending traditional techniques with modern sensibilities.',
		price: 392,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: apuntePaisajeAcuarela3
			}
		],
		year: 2020,
		dimensions: {
			width: 30,
			height: 33,
			unit: 'cm'
		},
		category: 'Landscape',
		isAvailable: true
	},
	{
		id: 'apunte-paisaje-acuarela-4',
		title: 'Apunte Paisaje Acuarela 4',
		description:
			'This artwork represents a unique perspective on contemporary themes, blending traditional techniques with modern sensibilities.',
		price: 598,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: apuntePaisajeAcuarela4
			}
		],
		year: 2019,
		dimensions: {
			width: 76,
			height: 74,
			unit: 'cm'
		},
		category: 'Mixed Media',
		isAvailable: true
	},
	{
		id: 'apunte-paisaje-acuarela-5',
		title: 'Apunte Paisaje Acuarela 5',
		description:
			'This artwork represents a unique perspective on contemporary themes, blending traditional techniques with modern sensibilities.',
		price: 1819,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: apuntePaisajeAcuarela5
			}
		],
		year: 2020,
		dimensions: {
			width: 47,
			height: 65,
			unit: 'cm'
		},
		category: 'Photography',
		isAvailable: true
	},
	{
		id: 'apunte-paisaje-collage-1',
		title: 'Apunte Paisaje Collage 1',
		description:
			"This artwork showcases the artist's mastery of technique while conveying deep emotional resonance.",
		price: 603,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: apuntePaisajeCollage1
			}
		],
		year: 2023,
		dimensions: {
			width: 26,
			height: 43,
			unit: 'cm'
		},
		category: 'Mixed Media',
		isAvailable: true
	},
	{
		id: 'apunte-paisaje-collage-2',
		title: 'Apunte Paisaje Collage 2',
		description:
			'This piece captures a moment in time with remarkable sensitivity and artistic insight.',
		price: 236,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: apuntePaisajeCollage2
			}
		],
		year: 2020,
		dimensions: {
			width: 35,
			height: 48,
			unit: 'cm'
		},
		category: 'Digital Art',
		isAvailable: true
	},
	{
		id: 'belong',
		title: 'Belong',
		description:
			'An engaging composition that balances technical excellence with creative vision and artistic integrity.',
		price: 1150,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: belong
			}
		],
		year: 2019,
		dimensions: {
			width: 25,
			height: 35,
			unit: 'cm'
		},
		category: 'Drawing',
		isAvailable: true
	},
	{
		id: 'celebes-sea',
		title: 'Celebes Sea',
		description:
			'An evocative work that invites contemplation and reflection through its subtle nuances and artistic expression.',
		price: 303,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: celebesSea
			},
			{
				name: 'zoom-1',
				picture: celebesSeaZoom1
			},
			{
				name: 'zoom-2',
				picture: celebesSeaZoom2
			}
		],
		year: 2018,
		dimensions: {
			width: 28,
			height: 45,
			unit: 'cm'
		},
		category: 'Landscape',
		isAvailable: true
	},
	{
		id: 'dama',
		title: 'Dama',
		description:
			'An evocative work that invites contemplation and reflection through its subtle nuances and artistic expression.',
		price: 620,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: dama
			}
		],
		year: 2020,
		dimensions: {
			width: 20,
			height: 44,
			unit: 'cm'
		},
		category: 'Collage',
		isAvailable: true
	},
	{
		id: 'estudio-retrato-1',
		title: 'Estudio Retrato 1',
		description:
			'An engaging composition that balances technical excellence with creative vision and artistic integrity.',
		price: 167,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: estudioRetrato1
			},
			{
				name: 'zoom-1',
				picture: estudioRetrato1Zoom1
			},
			{
				name: 'zoom-2',
				picture: estudioRetrato1Zoom2
			}
		],
		year: 2022,
		dimensions: {
			width: 24,
			height: 46,
			unit: 'cm'
		},
		category: 'Collage',
		isAvailable: true
	},
	{
		id: 'estudio-retrato-2',
		title: 'Estudio Retrato 2',
		description:
			'A stunning composition that captures the essence of its subject through bold colors and dynamic movement.',
		price: 2114,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: estudioRetrato2
			},
			{
				name: 'zoom-1',
				picture: estudioRetrato2Zoom1
			}
		],
		year: 2021,
		dimensions: {
			width: 21,
			height: 26,
			unit: 'cm'
		},
		category: 'Digital Art',
		isAvailable: true
	},
	{
		id: 'grafito-catedral',
		title: 'Grafito Catedral',
		description:
			'A captivating piece that explores the interplay of light and shadow, creating depth and emotion through masterful brushwork.',
		price: 2601,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: grafitoCatedral
			}
		],
		year: 2021,
		dimensions: {
			width: 84,
			height: 93,
			unit: 'cm'
		},
		category: 'Portrait',
		isAvailable: true
	},
	{
		id: 'hombre-con-barba',
		title: 'Hombre Con Barba',
		description:
			'This artwork represents a unique perspective on contemporary themes, blending traditional techniques with modern sensibilities.',
		price: 3241,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: hombreConBarba
			}
		],
		year: 2015,
		dimensions: {
			width: 50,
			height: 52,
			unit: 'cm'
		},
		category: 'Drawing',
		isAvailable: true
	},
	{
		id: 'lechera',
		title: 'Lechera',
		description:
			'This artwork represents a unique perspective on contemporary themes, blending traditional techniques with modern sensibilities.',
		price: 1262,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: lechera
			}
		],
		year: 2022,
		dimensions: {
			width: 69,
			height: 40,
			unit: 'cm'
		},
		category: 'Portrait',
		isAvailable: true
	},
	{
		id: 'lilith',
		title: 'Lilith',
		description:
			'This piece demonstrates exceptional skill in composition and color theory, creating a visually striking experience.',
		price: 338,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: lilith
			},
			{
				name: 'zoom-1',
				picture: lilithZoom1
			}
		],
		year: 2020,
		dimensions: {
			width: 30,
			height: 42,
			unit: 'cm'
		},
		category: 'Contemporary',
		isAvailable: true
	},
	{
		id: 'nuevos-acercamientos',
		title: 'Nuevos Acercamientos',
		description:
			'This piece captures a moment in time with remarkable sensitivity and artistic insight.',
		price: 202,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: nuevosAcercamientos
			}
		],
		year: 2019,
		dimensions: {
			width: 28,
			height: 42,
			unit: 'cm'
		},
		category: 'Landscape',
		isAvailable: true
	},
	{
		id: 'perpetuidad',
		title: 'Perpetuidad',
		description:
			'An engaging composition that balances technical excellence with creative vision and artistic integrity.',
		price: 251,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: perpetuidad
			}
		],
		year: 2020,
		dimensions: {
			width: 100,
			height: 118,
			unit: 'cm'
		},
		category: 'Contemporary',
		isAvailable: true
	},
	{
		id: 'retrato-anciano',
		title: 'Retrato Anciano',
		description:
			'A beautiful piece that harmonizes form and content, creating a lasting impression on the viewer.',
		price: 158,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: retratoAnciano
			}
		],
		year: 2016,
		dimensions: {
			width: 35,
			height: 26,
			unit: 'cm'
		},
		category: 'Portrait',
		isAvailable: true
	},
	{
		id: 'retrato-del-fayum',
		title: 'Retrato Del Fayum',
		description:
			'A stunning composition that captures the essence of its subject through bold colors and dynamic movement.',
		price: 4191,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: retratoDelFayum
			}
		],
		year: 2022,
		dimensions: {
			width: 59,
			height: 75,
			unit: 'cm'
		},
		category: 'Portrait',
		isAvailable: true
	},
	{
		id: 'retrato-sanguina',
		title: 'Retrato Sanguina',
		description:
			'A beautiful piece that harmonizes form and content, creating a lasting impression on the viewer.',
		price: 216,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: retratoSanguina
			}
		],
		year: 2018,
		dimensions: {
			width: 97,
			height: 99,
			unit: 'cm'
		},
		category: 'Digital Art',
		isAvailable: true
	},
	{
		id: 'summary',
		title: 'Summary',
		description:
			'An engaging composition that balances technical excellence with creative vision and artistic integrity.',
		price: 2778,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: summary
			}
		],
		year: 2020,
		dimensions: {
			width: 29,
			height: 28,
			unit: 'cm'
		},
		category: 'Digital Art',
		isAvailable: true
	},
	{
		id: 'the-joke',
		title: 'The Joke',
		description:
			'This piece demonstrates exceptional skill in composition and color theory, creating a visually striking experience.',
		price: 4621,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: theJoke
			}
		],
		year: 2020,
		dimensions: {
			width: 23,
			height: 48,
			unit: 'cm'
		},
		category: 'Digital Art',
		isAvailable: true
	},
	{
		id: 'the-rockero',
		title: 'The Rockero',
		description:
			'An engaging composition that balances technical excellence with creative vision and artistic integrity.',
		price: 1147,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: theRockero
			}
		],
		year: 2017,
		dimensions: {
			width: 51,
			height: 58,
			unit: 'cm'
		},
		category: 'Photography',
		isAvailable: true
	},
	{
		id: 'time-after-time',
		title: 'Time After Time',
		description:
			'An evocative work that invites contemplation and reflection through its subtle nuances and artistic expression.',
		price: 854,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: timeAfterTime
			}
		],
		year: 2021,
		dimensions: {
			width: 67,
			height: 54,
			unit: 'cm'
		},
		category: 'Landscape',
		isAvailable: true
	},
	{
		id: 'tragaluz',
		title: 'Tragaluz',
		description:
			'An engaging composition that balances technical excellence with creative vision and artistic integrity.',
		price: 334,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: tragaluz
			}
		],
		year: 2021,
		dimensions: {
			width: 20,
			height: 48,
			unit: 'cm'
		},
		category: 'Digital Art',
		isAvailable: true
	},
	{
		id: 'xauen',
		title: 'Xauen',
		description:
			'This piece captures a moment in time with remarkable sensitivity and artistic insight.',
		price: 430,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				picture: xauen
			}
		],
		year: 2022,
		dimensions: {
			width: 53,
			height: 41,
			unit: 'cm'
		},
		category: 'Digital Art',
		isAvailable: true
	}
];

// Helper functions
export function getArtworkById(id: string): Artwork | undefined {
	return artworkData.find((artwork) => artwork.id === id);
}

export function getArtworksByCategory(category: string): Artwork[] {
	return artworkData.filter((artwork) => artwork.category === category);
}

export function getAvailableCategories(): string[] {
	const categories = new Set(artworkData.map((artwork) => artwork.category));
	return Array.from(categories).sort();
}

export function getRandomArtwork(): Artwork {
	const randomIndex = Math.floor(Math.random() * artworkData.length);
	return artworkData[randomIndex];
}
