/**
 * Generated artwork images data
 * This file is automatically generated from static images
 * DO NOT EDIT MANUALLY - Run 'npm run generate-artwork-images' to regenerate
 */

export const artworkImages = {
	albor: [
		{ name: 'main', src: '/images/albor.webp', alt: 'Albor main view' },
		{ name: 'zoom-1', src: '/images/albor-zoom-1.webp', alt: 'Albor zoom detail 1' }
	],
	'alcon-collage': [
		{ name: 'main', src: '/images/alcon-collage.webp', alt: 'Alcon Collage main view' }
	],
	'apunte-abstracto-1': [
		{ name: 'main', src: '/images/apunte-abstracto-1.webp', alt: 'Apunte Abstracto 1 main view' }
	],
	'apunte-abstracto-2': [
		{ name: 'main', src: '/images/apunte-abstracto-2.webp', alt: 'Apunte Abstracto 2 main view' }
	],
	'apunte-abstracto-3': [
		{ name: 'main', src: '/images/apunte-abstracto-3.webp', alt: 'Apunte Abstracto 3 main view' }
	],
	'apunte-acrilico-1': [
		{ name: 'main', src: '/images/apunte-acrilico-1.webp', alt: 'Apunte Acrilico 1 main view' }
	],
	'apunte-acrilico-2': [
		{ name: 'main', src: '/images/apunte-acrilico-2.webp', alt: 'Apunte Acrilico 2 main view' },
		{
			name: 'zoom-1',
			src: '/images/apunte-acrilico-2-zoom-1.webp',
			alt: 'Apunte Acrilico 2 zoom detail 1'
		}
	],
	'apunte-acrilico-3': [
		{ name: 'main', src: '/images/apunte-acrilico-3.webp', alt: 'Apunte Acrilico 3 main view' }
	],
	'apunte-acrilico-4': [
		{ name: 'main', src: '/images/apunte-acrilico-4.webp', alt: 'Apunte Acrilico 4 main view' }
	],
	'apunte-acuarela-paloma': [
		{
			name: 'main',
			src: '/images/apunte-acuarela-paloma.webp',
			alt: 'Apunte Acuarela Paloma main view'
		}
	],
	'apunte-baeza-acuerela': [
		{
			name: 'main',
			src: '/images/apunte-baeza-acuerela.webp',
			alt: 'Apunte Baeza Acuerela main view'
		}
	],
	'apunte-grafito': [
		{ name: 'main', src: '/images/apunte-grafito.webp', alt: 'Apunte Grafito main view' }
	],
	'apunte-paisaje-acuarela-1': [
		{
			name: 'main',
			src: '/images/apunte-paisaje-acuarela-1.webp',
			alt: 'Apunte Paisaje Acuarela 1 main view'
		}
	],
	'apunte-paisaje-acuarela-3': [
		{
			name: 'main',
			src: '/images/apunte-paisaje-acuarela-3.webp',
			alt: 'Apunte Paisaje Acuarela 3 main view'
		}
	],
	'apunte-paisaje-acuarela-4': [
		{
			name: 'main',
			src: '/images/apunte-paisaje-acuarela-4.webp',
			alt: 'Apunte Paisaje Acuarela 4 main view'
		}
	],
	'apunte-paisaje-acuarela-5': [
		{
			name: 'main',
			src: '/images/apunte-paisaje-acuarela-5.webp',
			alt: 'Apunte Paisaje Acuarela 5 main view'
		}
	],
	'apunte-paisaje-collage-1': [
		{
			name: 'main',
			src: '/images/apunte-paisaje-collage-1.webp',
			alt: 'Apunte Paisaje Collage 1 main view'
		}
	],
	'apunte-paisaje-collage-2': [
		{
			name: 'main',
			src: '/images/apunte-paisaje-collage-2.webp',
			alt: 'Apunte Paisaje Collage 2 main view'
		}
	],
	belong: [{ name: 'main', src: '/images/belong.webp', alt: 'Belong main view' }],
	'celebes-sea': [
		{ name: 'main', src: '/images/celebes-sea.webp', alt: 'Celebes Sea main view' },
		{ name: 'zoom-1', src: '/images/celebes-sea-zoom-1.webp', alt: 'Celebes Sea zoom detail 1' },
		{ name: 'zoom-2', src: '/images/celebes-sea-zoom-2.webp', alt: 'Celebes Sea zoom detail 2' },
		{ name: 'zoom-3', src: '/images/celebes-sea-zoom-3.webp', alt: 'Celebes Sea zoom detail 3' }
	],
	'dama-acuarela': [
		{ name: 'main', src: '/images/dama-acuarela.webp', alt: 'Dama Acuarela main view' },
		{ name: 'zoom-1', src: '/images/dama-acuarela-zoom-1.webp', alt: 'Dama Acuarela zoom detail 1' }
	],
	dama: [{ name: 'main', src: '/images/dama.webp', alt: 'Dama main view' }],
	'estudio-anatomia': [
		{ name: 'main', src: '/images/estudio-anatomia.webp', alt: 'Estudio Anatomia main view' },
		{
			name: 'zoom-1',
			src: '/images/estudio-anatomia-zoom-1.webp',
			alt: 'Estudio Anatomia zoom detail 1'
		}
	],
	'estudio-retrato-1': [
		{ name: 'main', src: '/images/estudio-retrato-1.webp', alt: 'Estudio Retrato 1 main view' },
		{
			name: 'zoom-1',
			src: '/images/estudio-retrato-1-zoom-1.webp',
			alt: 'Estudio Retrato 1 zoom detail 1'
		},
		{
			name: 'zoom-2',
			src: '/images/estudio-retrato-1-zoom-2.webp',
			alt: 'Estudio Retrato 1 zoom detail 2'
		}
	],
	'estudio-retrato-2': [
		{ name: 'main', src: '/images/estudio-retrato-2.webp', alt: 'Estudio Retrato 2 main view' },
		{
			name: 'zoom-1',
			src: '/images/estudio-retrato-2-zoom-1.webp',
			alt: 'Estudio Retrato 2 zoom detail 1'
		},
		{
			name: 'zoom-2',
			src: '/images/estudio-retrato-2-zoom-2.webp',
			alt: 'Estudio Retrato 2 zoom detail 2'
		}
	],
	'grafito-catedral': [
		{ name: 'main', src: '/images/grafito-catedral.webp', alt: 'Grafito Catedral main view' }
	],
	'hombre-con-barba': [
		{ name: 'main', src: '/images/hombre-con-barba.webp', alt: 'Hombre Con Barba main view' }
	],
	inherente: [{ name: 'main', src: '/images/inherente.webp', alt: 'Inherente main view' }],
	lechera: [{ name: 'main', src: '/images/lechera.webp', alt: 'Lechera main view' }],
	notional: [
		{ name: 'zoom-1', src: '/images/notional-zoom-1.webp', alt: 'Notional zoom detail 1' },
		{ name: 'zoom-2', src: '/images/notional-zoom-2.webp', alt: 'Notional zoom detail 2' }
	],
	'nuevos-acercamientos': [
		{
			name: 'main',
			src: '/images/nuevos-acercamientos.webp',
			alt: 'Nuevos Acercamientos main view'
		}
	],
	perpetuidad: [{ name: 'main', src: '/images/perpetuidad.webp', alt: 'Perpetuidad main view' }],
	provecto: [
		{ name: 'main', src: '/images/provecto.webp', alt: 'Provecto main view' },
		{ name: 'zoom-1', src: '/images/provecto-zoom-1.webp', alt: 'Provecto zoom detail 1' }
	],
	'retrato-del-fayum': [
		{ name: 'main', src: '/images/retrato-del-fayum.webp', alt: 'Retrato Del Fayum main view' }
	],
	'retrato-sanguina': [
		{ name: 'main', src: '/images/retrato-sanguina.webp', alt: 'Retrato Sanguina main view' }
	],
	summary: [{ name: 'main', src: '/images/summary.webp', alt: 'Summary main view' }],
	'the-joke': [{ name: 'main', src: '/images/the-joke.webp', alt: 'The Joke main view' }],
	'the-rockero': [{ name: 'main', src: '/images/the-rockero.webp', alt: 'The Rockero main view' }],
	theophany: [{ name: 'main', src: '/images/theophany.webp', alt: 'Theophany main view' }],
	'time-after-time': [
		{ name: 'main', src: '/images/time-after-time.webp', alt: 'Time After Time main view' }
	],
	tragaluz: [{ name: 'main', src: '/images/tragaluz.webp', alt: 'Tragaluz main view' }],
	vetusto: [
		{ name: 'main', src: '/images/vetusto.webp', alt: 'Vetusto main view' },
		{ name: 'zoom-1', src: '/images/vetusto-zoom-1.webp', alt: 'Vetusto zoom detail 1' }
	],
	xauen: [{ name: 'main', src: '/images/xauen.webp', alt: 'Xauen main view' }],
	zalema: [{ name: 'main', src: '/images/zalema.webp', alt: 'Zalema main view' }]
};

export type ArtworkImages = typeof artworkImages;
