// Auto-generated artwork data - 2025-09-24T14:36:32.527Z
// This file is automatically generated from images in src/lib/assets/images/
// To regenerate, run: npm run generate:artwork-data

import type { Artwork } from '$lib/types/artwork';

export const artworkData: Artwork[] = [
	{
		id: 'acrilico-1',
		title: 'Acrilico 1',
		description:
			'A beautiful piece that harmonizes form and content, creating a lasting impression on the viewer.',
		price: 808,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/acrilico-1.webp',
				fullUrl: '/images/acrilico-1.webp'
			},
			{
				name: 'zoom-1',
				thumbnailUrl: '/images/acrilico-1-zoom-1.webp',
				fullUrl: '/images/acrilico-1-zoom-1.webp'
			}
		],
		year: 2022,
		dimensions: {
			width: 37,
			height: 49,
			unit: 'cm'
		},
		category: 'Portrait',
		isAvailable: true
	},
	{
		id: 'albor',
		title: 'Albor',
		description:
			'This work demonstrates innovative approaches to traditional artistic concepts, resulting in a fresh perspective.',
		price: 3057,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/albor.webp',
				fullUrl: '/images/albor.webp'
			},
			{
				name: 'zoom-1',
				thumbnailUrl: '/images/albor-zoom-1.webp',
				fullUrl: '/images/albor-zoom-1.webp'
			}
		],
		year: 2016,
		dimensions: {
			width: 53,
			height: 40,
			unit: 'cm'
		},
		category: 'Mixed Media',
		isAvailable: true
	},
	{
		id: 'alcon-collage',
		title: 'Alcon Collage',
		description:
			'A stunning composition that captures the essence of its subject through bold colors and dynamic movement.',
		price: 568,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/alcon-collage.webp',
				fullUrl: '/images/alcon-collage.webp'
			}
		],
		year: 2023,
		dimensions: {
			width: 76,
			height: 71,
			unit: 'cm'
		},
		category: 'Landscape',
		isAvailable: true
	},
	{
		id: 'apunte-abstracto-1',
		title: 'Apunte Abstracto 1',
		description:
			'An evocative work that invites contemplation and reflection through its subtle nuances and artistic expression.',
		price: 204,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/apunte-abstracto-1.webp',
				fullUrl: '/images/apunte-abstracto-1.webp'
			}
		],
		year: 2017,
		dimensions: {
			width: 33,
			height: 37,
			unit: 'cm'
		},
		category: 'Collage',
		isAvailable: true
	},
	{
		id: 'apunte-abstracto-2',
		title: 'Apunte Abstracto 2',
		description:
			'A captivating piece that explores the interplay of light and shadow, creating depth and emotion through masterful brushwork.',
		price: 197,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/apunte-abstracto-2.webp',
				fullUrl: '/images/apunte-abstracto-2.webp'
			}
		],
		year: 2022,
		dimensions: {
			width: 37,
			height: 64,
			unit: 'cm'
		},
		category: 'Mixed Media',
		isAvailable: true
	},
	{
		id: 'apunte-abstracto-3',
		title: 'Apunte Abstracto 3',
		description:
			'This piece captures a moment in time with remarkable sensitivity and artistic insight.',
		price: 260,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/apunte-abstracto-3.webp',
				fullUrl: '/images/apunte-abstracto-3.webp'
			}
		],
		year: 2020,
		dimensions: {
			width: 27,
			height: 39,
			unit: 'cm'
		},
		category: 'Painting',
		isAvailable: true
	},
	{
		id: 'apunte-baeza-acuerela',
		title: 'Apunte Baeza Acuerela',
		description:
			'This piece demonstrates exceptional skill in composition and color theory, creating a visually striking experience.',
		price: 1531,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/apunte-baeza-acuerela.webp',
				fullUrl: '/images/apunte-baeza-acuerela.webp'
			}
		],
		year: 2022,
		dimensions: {
			width: 30,
			height: 63,
			unit: 'cm'
		},
		category: 'Drawing',
		isAvailable: true
	},
	{
		id: 'apunte-paisaje-acrilico',
		title: 'Apunte Paisaje Acrilico',
		description:
			'This piece demonstrates exceptional skill in composition and color theory, creating a visually striking experience.',
		price: 623,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/apunte-paisaje-acrilico.webp',
				fullUrl: '/images/apunte-paisaje-acrilico.webp'
			}
		],
		year: 2023,
		dimensions: {
			width: 32,
			height: 34,
			unit: 'cm'
		},
		category: 'Drawing',
		isAvailable: true
	},
	{
		id: 'apunte-paisaje-acuarela-1',
		title: 'Apunte Paisaje Acuarela 1',
		description:
			'This work demonstrates innovative approaches to traditional artistic concepts, resulting in a fresh perspective.',
		price: 189,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/apunte-paisaje-acuarela-1.webp',
				fullUrl: '/images/apunte-paisaje-acuarela-1.webp'
			}
		],
		year: 2022,
		dimensions: {
			width: 44,
			height: 54,
			unit: 'cm'
		},
		category: 'Contemporary',
		isAvailable: true
	},
	{
		id: 'apunte-paisaje-acuarela-3',
		title: 'Apunte Paisaje Acuarela 3',
		description:
			'An evocative work that invites contemplation and reflection through its subtle nuances and artistic expression.',
		price: 1706,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/apunte-paisaje-acuarela-3.webp',
				fullUrl: '/images/apunte-paisaje-acuarela-3.webp'
			}
		],
		year: 2016,
		dimensions: {
			width: 63,
			height: 37,
			unit: 'cm'
		},
		category: 'Drawing',
		isAvailable: true
	},
	{
		id: 'apunte-paisaje-acuarela-4',
		title: 'Apunte Paisaje Acuarela 4',
		description:
			'This piece captures a moment in time with remarkable sensitivity and artistic insight.',
		price: 809,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/apunte-paisaje-acuarela-4.webp',
				fullUrl: '/images/apunte-paisaje-acuarela-4.webp'
			}
		],
		year: 2020,
		dimensions: {
			width: 79,
			height: 79,
			unit: 'cm'
		},
		category: 'Digital Art',
		isAvailable: true
	},
	{
		id: 'apunte-paisaje-acuarela-5',
		title: 'Apunte Paisaje Acuarela 5',
		description:
			'A beautiful piece that harmonizes form and content, creating a lasting impression on the viewer.',
		price: 474,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/apunte-paisaje-acuarela-5.webp',
				fullUrl: '/images/apunte-paisaje-acuarela-5.webp'
			}
		],
		year: 2022,
		dimensions: {
			width: 66,
			height: 37,
			unit: 'cm'
		},
		category: 'Mixed Media',
		isAvailable: true
	},
	{
		id: 'apunte-paisaje-collage-1',
		title: 'Apunte Paisaje Collage 1',
		description:
			'This artwork represents a unique perspective on contemporary themes, blending traditional techniques with modern sensibilities.',
		price: 2866,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/apunte-paisaje-collage-1.webp',
				fullUrl: '/images/apunte-paisaje-collage-1.webp'
			}
		],
		year: 2018,
		dimensions: {
			width: 79,
			height: 53,
			unit: 'cm'
		},
		category: 'Digital Art',
		isAvailable: true
	},
	{
		id: 'apunte-paisaje-collage-2',
		title: 'Apunte Paisaje Collage 2',
		description:
			'This piece captures a moment in time with remarkable sensitivity and artistic insight.',
		price: 728,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/apunte-paisaje-collage-2.webp',
				fullUrl: '/images/apunte-paisaje-collage-2.webp'
			}
		],
		year: 2020,
		dimensions: {
			width: 56,
			height: 81,
			unit: 'cm'
		},
		category: 'Portrait',
		isAvailable: true
	},
	{
		id: 'belong',
		title: 'Belong',
		description:
			'A captivating piece that explores the interplay of light and shadow, creating depth and emotion through masterful brushwork.',
		price: 276,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/belong.webp',
				fullUrl: '/images/belong.webp'
			}
		],
		year: 2023,
		dimensions: {
			width: 53,
			height: 69,
			unit: 'cm'
		},
		category: 'Digital Art',
		isAvailable: true
	},
	{
		id: 'celebes-sea',
		title: 'Celebes Sea',
		description:
			'This piece captures a moment in time with remarkable sensitivity and artistic insight.',
		price: 4442,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/celebes-sea.webp',
				fullUrl: '/images/celebes-sea.webp'
			},
			{
				name: 'zoom-1',
				thumbnailUrl: '/images/celebes-sea-zoom-1.webp',
				fullUrl: '/images/celebes-sea-zoom-1.webp'
			},
			{
				name: 'zoom-2',
				thumbnailUrl: '/images/celebes-sea-zoom-2.webp',
				fullUrl: '/images/celebes-sea-zoom-2.webp'
			}
		],
		year: 2017,
		dimensions: {
			width: 80,
			height: 45,
			unit: 'cm'
		},
		category: 'Portrait',
		isAvailable: true
	},
	{
		id: 'dama',
		title: 'Dama',
		description:
			'An evocative work that invites contemplation and reflection through its subtle nuances and artistic expression.',
		price: 752,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/dama.webp',
				fullUrl: '/images/dama.webp'
			}
		],
		year: 2020,
		dimensions: {
			width: 47,
			height: 67,
			unit: 'cm'
		},
		category: 'Collage',
		isAvailable: true
	},
	{
		id: 'estudio-retrato-1',
		title: 'Estudio Retrato 1',
		description:
			'A stunning composition that captures the essence of its subject through bold colors and dynamic movement.',
		price: 273,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/estudio-retrato-1.webp',
				fullUrl: '/images/estudio-retrato-1.webp'
			},
			{
				name: 'zoom-1',
				thumbnailUrl: '/images/estudio-retrato-1-zoom-1.webp',
				fullUrl: '/images/estudio-retrato-1-zoom-1.webp'
			},
			{
				name: 'zoom-2',
				thumbnailUrl: '/images/estudio-retrato-1-zoom-2.webp',
				fullUrl: '/images/estudio-retrato-1-zoom-2.webp'
			}
		],
		year: 2023,
		dimensions: {
			width: 85,
			height: 103,
			unit: 'cm'
		},
		category: 'Landscape',
		isAvailable: true
	},
	{
		id: 'estudio-retrato-2',
		title: 'Estudio Retrato 2',
		description:
			'A beautiful piece that harmonizes form and content, creating a lasting impression on the viewer.',
		price: 989,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/estudio-retrato-2.webp',
				fullUrl: '/images/estudio-retrato-2.webp'
			},
			{
				name: 'zoom-1',
				thumbnailUrl: '/images/estudio-retrato-2-zoom-1.webp',
				fullUrl: '/images/estudio-retrato-2-zoom-1.webp'
			}
		],
		year: 2018,
		dimensions: {
			width: 58,
			height: 58,
			unit: 'cm'
		},
		category: 'Abstract',
		isAvailable: true
	},
	{
		id: 'grafito-catedral',
		title: 'Grafito Catedral',
		description:
			"This artwork showcases the artist's mastery of technique while conveying deep emotional resonance.",
		price: 593,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/grafito-catedral.webp',
				fullUrl: '/images/grafito-catedral.webp'
			}
		],
		year: 2024,
		dimensions: {
			width: 66,
			height: 52,
			unit: 'cm'
		},
		category: 'Drawing',
		isAvailable: true
	},
	{
		id: 'hombre-con-barba',
		title: 'Hombre Con Barba',
		description:
			'This piece demonstrates exceptional skill in composition and color theory, creating a visually striking experience.',
		price: 455,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/hombre-con-barba.webp',
				fullUrl: '/images/hombre-con-barba.webp'
			}
		],
		year: 2015,
		dimensions: {
			width: 35,
			height: 31,
			unit: 'cm'
		},
		category: 'Painting',
		isAvailable: true
	},
	{
		id: 'lechera',
		title: 'Lechera',
		description:
			'This piece captures a moment in time with remarkable sensitivity and artistic insight.',
		price: 221,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/lechera.webp',
				fullUrl: '/images/lechera.webp'
			}
		],
		year: 2015,
		dimensions: {
			width: 53,
			height: 47,
			unit: 'cm'
		},
		category: 'Abstract',
		isAvailable: true
	},
	{
		id: 'lilith',
		title: 'Lilith',
		description:
			'An engaging composition that balances technical excellence with creative vision and artistic integrity.',
		price: 1226,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/lilith.webp',
				fullUrl: '/images/lilith.webp'
			},
			{
				name: 'zoom-1',
				thumbnailUrl: '/images/lilith-zoom-1.webp',
				fullUrl: '/images/lilith-zoom-1.webp'
			}
		],
		year: 2020,
		dimensions: {
			width: 76,
			height: 83,
			unit: 'cm'
		},
		category: 'Drawing',
		isAvailable: true
	},
	{
		id: 'nuevos-acercamientos',
		title: 'Nuevos Acercamientos',
		description:
			'This work demonstrates innovative approaches to traditional artistic concepts, resulting in a fresh perspective.',
		price: 4156,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/nuevos-acercamientos.webp',
				fullUrl: '/images/nuevos-acercamientos.webp'
			}
		],
		year: 2020,
		dimensions: {
			width: 29,
			height: 47,
			unit: 'cm'
		},
		category: 'Photography',
		isAvailable: true
	},
	{
		id: 'perpetuidad',
		title: 'Perpetuidad',
		description:
			'An engaging composition that balances technical excellence with creative vision and artistic integrity.',
		price: 859,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/perpetuidad.webp',
				fullUrl: '/images/perpetuidad.webp'
			}
		],
		year: 2019,
		dimensions: {
			width: 44,
			height: 60,
			unit: 'cm'
		},
		category: 'Abstract',
		isAvailable: true
	},
	{
		id: 'retrato-anciano',
		title: 'Retrato Anciano',
		description:
			'An engaging composition that balances technical excellence with creative vision and artistic integrity.',
		price: 3462,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/retrato-anciano.webp',
				fullUrl: '/images/retrato-anciano.webp'
			}
		],
		year: 2017,
		dimensions: {
			width: 75,
			height: 54,
			unit: 'cm'
		},
		category: 'Digital Art',
		isAvailable: true
	},
	{
		id: 'retrato-del-fayum',
		title: 'Retrato Del Fayum',
		description:
			'This artwork represents a unique perspective on contemporary themes, blending traditional techniques with modern sensibilities.',
		price: 204,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/retrato-del-fayum.webp',
				fullUrl: '/images/retrato-del-fayum.webp'
			}
		],
		year: 2024,
		dimensions: {
			width: 33,
			height: 40,
			unit: 'cm'
		},
		category: 'Photography',
		isAvailable: true
	},
	{
		id: 'retrato-sanguina',
		title: 'Retrato Sanguina',
		description:
			'An engaging composition that balances technical excellence with creative vision and artistic integrity.',
		price: 1252,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/retrato-sanguina.webp',
				fullUrl: '/images/retrato-sanguina.webp'
			}
		],
		year: 2022,
		dimensions: {
			width: 26,
			height: 26,
			unit: 'cm'
		},
		category: 'Collage',
		isAvailable: true
	},
	{
		id: 'summary',
		title: 'Summary',
		description:
			'An engaging composition that balances technical excellence with creative vision and artistic integrity.',
		price: 962,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/summary.webp',
				fullUrl: '/images/summary.webp'
			}
		],
		year: 2018,
		dimensions: {
			width: 25,
			height: 41,
			unit: 'cm'
		},
		category: 'Photography',
		isAvailable: true
	},
	{
		id: 'the-joke',
		title: 'The Joke',
		description:
			"This artwork showcases the artist's mastery of technique while conveying deep emotional resonance.",
		price: 188,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/the-joke.webp',
				fullUrl: '/images/the-joke.webp'
			}
		],
		year: 2022,
		dimensions: {
			width: 35,
			height: 40,
			unit: 'cm'
		},
		category: 'Photography',
		isAvailable: true
	},
	{
		id: 'the-rockero',
		title: 'The Rockero',
		description:
			'This piece captures a moment in time with remarkable sensitivity and artistic insight.',
		price: 2122,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/the-rockero.webp',
				fullUrl: '/images/the-rockero.webp'
			}
		],
		year: 2024,
		dimensions: {
			width: 24,
			height: 32,
			unit: 'cm'
		},
		category: 'Painting',
		isAvailable: true
	},
	{
		id: 'time-after-time',
		title: 'Time After Time',
		description:
			'This piece demonstrates exceptional skill in composition and color theory, creating a visually striking experience.',
		price: 846,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/time-after-time.webp',
				fullUrl: '/images/time-after-time.webp'
			}
		],
		year: 2015,
		dimensions: {
			width: 53,
			height: 32,
			unit: 'cm'
		},
		category: 'Contemporary',
		isAvailable: true
	},
	{
		id: 'tragaluz',
		title: 'Tragaluz',
		description:
			'This piece captures a moment in time with remarkable sensitivity and artistic insight.',
		price: 174,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/tragaluz.webp',
				fullUrl: '/images/tragaluz.webp'
			}
		],
		year: 2018,
		dimensions: {
			width: 47,
			height: 56,
			unit: 'cm'
		},
		category: 'Drawing',
		isAvailable: true
	},
	{
		id: 'xauen',
		title: 'Xauen',
		description:
			'A stunning composition that captures the essence of its subject through bold colors and dynamic movement.',
		price: 780,
		currency: 'EUR',
		images: [
			{
				name: 'main',
				thumbnailUrl: '/images/xauen.webp',
				fullUrl: '/images/xauen.webp'
			}
		],
		year: 2015,
		dimensions: {
			width: 51,
			height: 47,
			unit: 'cm'
		},
		category: 'Contemporary',
		isAvailable: true
	}
];

// Helper functions
export function getArtworkById(id: string): Artwork | undefined {
	return artworkData.find((artwork) => artwork.id === id);
}

export function getArtworksByCategory(category: string): Artwork[] {
	return artworkData.filter((artwork) => artwork.category === category);
}

export function getAvailableCategories(): string[] {
	const categories = new Set(artworkData.map((artwork) => artwork.category));
	return Array.from(categories).sort();
}

export function getRandomArtwork(): Artwork {
	const randomIndex = Math.floor(Math.random() * artworkData.length);
	return artworkData[randomIndex];
}
