// Auto-generated enhanced image imports and artwork data - 2025-09-26T09:12:39.778Z
// This file is automatically generated from images in src/lib/assets/images/
// To regenerate, run: npm run generate:enhanced-imports
//
// This file contains proper enhanced image imports using the ?enhanced parameter
// which creates Picture objects compatible with Svelte's enhanced:img component

import type { Artwork } from '$lib/types/artwork';

import albor_zoom_1 from '$lib/assets/images/albor-zoom-1.webp?enhanced';
import albor from '$lib/assets/images/albor.webp?enhanced';
import alcon_collage from '$lib/assets/images/alcon-collage.webp?enhanced';
import apunte_abstracto_1 from '$lib/assets/images/apunte-abstracto-1.webp?enhanced';
import apunte_abstracto_2 from '$lib/assets/images/apunte-abstracto-2.webp?enhanced';
import apunte_abstracto_3 from '$lib/assets/images/apunte-abstracto-3.webp?enhanced';
import apunte_acrilico_1 from '$lib/assets/images/apunte-acrilico-1.webp?enhanced';
import apunte_acrilico_2 from '$lib/assets/images/apunte-acrilico-2.webp?enhanced';
import apunte_acrilico_3 from '$lib/assets/images/apunte-acrilico-3.webp?enhanced';
import apunte_acr_lico_2_zoom_1 from '$lib/assets/images/apunte-acrílico-2-zoom-1.webp?enhanced';
import apunte_acr_lico_4 from '$lib/assets/images/apunte-acrílico-4.webp?enhanced';
import apunte_acuarela_paloma from '$lib/assets/images/apunte-acuarela-paloma.webp?enhanced';
import apunte_baeza_acuerela from '$lib/assets/images/apunte-baeza-acuerela.webp?enhanced';
import apunte_grafito from '$lib/assets/images/apunte-grafito.webp?enhanced';
import apunte_paisaje_acuarela_1 from '$lib/assets/images/apunte-paisaje-acuarela-1.webp?enhanced';
import apunte_paisaje_acuarela_3 from '$lib/assets/images/apunte-paisaje-acuarela-3.webp?enhanced';
import apunte_paisaje_acuarela_4 from '$lib/assets/images/apunte-paisaje-acuarela-4.webp?enhanced';
import apunte_paisaje_acuarela_5 from '$lib/assets/images/apunte-paisaje-acuarela-5.webp?enhanced';
import apunte_paisaje_collage_1 from '$lib/assets/images/apunte-paisaje-collage-1.webp?enhanced';
import apunte_paisaje_collage_2 from '$lib/assets/images/apunte-paisaje-collage-2.webp?enhanced';
import belong from '$lib/assets/images/belong.webp?enhanced';
import celebes_sea_zoom_1 from '$lib/assets/images/celebes-sea-zoom-1.webp?enhanced';
import celebes_sea_zoom_2 from '$lib/assets/images/celebes-sea-zoom-2.webp?enhanced';
import celebes_sea_zoom_3 from '$lib/assets/images/celebes-sea-zoom-3.webp?enhanced';
import celebes_sea from '$lib/assets/images/celebes-sea.webp?enhanced';
import dama_acuarela_zoom_1 from '$lib/assets/images/dama-acuarela-zoom-1.webp?enhanced';
import dama_acuarela from '$lib/assets/images/dama-acuarela.webp?enhanced';
import dama from '$lib/assets/images/dama.webp?enhanced';
import estudio_anatomia_zoom_1 from '$lib/assets/images/estudio-anatomia-zoom-1.webp?enhanced';
import estudio_anatomia from '$lib/assets/images/estudio-anatomia.webp?enhanced';
import estudio_retrato_1_zoom_1 from '$lib/assets/images/estudio-retrato-1-zoom-1.webp?enhanced';
import estudio_retrato_1_zoom_2 from '$lib/assets/images/estudio-retrato-1-zoom-2.webp?enhanced';
import estudio_retrato_1 from '$lib/assets/images/estudio-retrato-1.webp?enhanced';
import estudio_retrato_2_zoom_1 from '$lib/assets/images/estudio-retrato-2-zoom-1.webp?enhanced';
import estudio_retrato_2_zoom_2 from '$lib/assets/images/estudio-retrato-2-zoom-2.webp?enhanced';
import estudio_retrato_2 from '$lib/assets/images/estudio-retrato-2.webp?enhanced';
import grafito_catedral from '$lib/assets/images/grafito-catedral.webp?enhanced';
import hombre_con_barba from '$lib/assets/images/hombre-con-barba.webp?enhanced';
import inherente from '$lib/assets/images/inherente.webp?enhanced';
import lechera from '$lib/assets/images/lechera.webp?enhanced';
import notional_zoom_1 from '$lib/assets/images/notional-zoom-1.webp?enhanced';
import notional_zoom_2 from '$lib/assets/images/notional-zoom-2.webp?enhanced';
import nuevos_acercamientos from '$lib/assets/images/nuevos-acercamientos.webp?enhanced';
import perpetuidad from '$lib/assets/images/perpetuidad.webp?enhanced';
import provecto_zoom_1 from '$lib/assets/images/provecto-zoom-1.webp?enhanced';
import provecto from '$lib/assets/images/provecto.webp?enhanced';
import retrato_del_fayum from '$lib/assets/images/retrato-del-fayum.webp?enhanced';
import retrato_sanguina from '$lib/assets/images/retrato-sanguina.webp?enhanced';
import summary from '$lib/assets/images/summary.webp?enhanced';
import the_joke from '$lib/assets/images/the-joke.webp?enhanced';
import the_rockero from '$lib/assets/images/the-rockero.webp?enhanced';
import theophany from '$lib/assets/images/theophany.webp?enhanced';
import time_after_time from '$lib/assets/images/time-after-time.webp?enhanced';
import tragaluz from '$lib/assets/images/tragaluz.webp?enhanced';
import vetusto_zoom_1 from '$lib/assets/images/vetusto-zoom-1.webp?enhanced';
import vetusto from '$lib/assets/images/vetusto.webp?enhanced';
import xauen from '$lib/assets/images/xauen.webp?enhanced';
import zalema from '$lib/assets/images/zalema.webp?enhanced';

export const artworkData: Artwork[] = [
	{
		id: "albor",
		title: "Albor",
		images: [
		{
			name: "main",
			picture: albor
		},
		{
			name: "zoom-1",
			picture: albor_zoom_1
		}
		],
		category: "pintura",
		isAvailable: false
	},
	{
		id: "alcon-collage",
		title: "Alcon Collage",
		images: [
		{
			name: "main",
			picture: alcon_collage
		}
		],
		category: ["pintura", "apunte"],
		isAvailable: false
	},
	{
		id: "apunte-abstracto-1",
		title: "Apunte Abstracto 1",
		images: [
		{
			name: "main",
			picture: apunte_abstracto_1
		}
		],
		category: ["apunte", "pintura"],
		isAvailable: false
	},
	{
		id: "apunte-abstracto-2",
		title: "Apunte Abstracto 2",
		images: [
		{
			name: "main",
			picture: apunte_abstracto_2
		}
		],
		category: ["apunte", "pintura"],
		isAvailable: false
	},
	{
		id: "apunte-abstracto-3",
		title: "Apunte Abstracto 3",
		images: [
		{
			name: "main",
			picture: apunte_abstracto_3
		}
		],
		category: ["apunte", "pintura"],
		isAvailable: false
	},
	{
		id: "apunte-acrilico-1",
		title: "Apunte Acrilico 1",
		images: [
		{
			name: "main",
			picture: apunte_acrilico_1
		}
		],
		category: ["apunte", "pintura"],
		isAvailable: false
	},
	{
		id: "apunte-acrilico-2",
		title: "Apunte Acrilico 2",
		images: [
		{
			name: "main",
			picture: apunte_acrilico_2
		}
		],
		category: ["apunte", "pintura"],
		isAvailable: false
	},
	{
		id: "apunte-acrilico-3",
		title: "Apunte Acrilico 3",
		images: [
		{
			name: "main",
			picture: apunte_acrilico_3
		}
		],
		category: ["apunte", "pintura"],
		isAvailable: false
	},
	{
		id: "apunte-acrílico-2",
		title: "Apunte Acrílico 2",
		images: [
		{
			name: "zoom-1",
			picture: apunte_acr_lico_2_zoom_1
		}
		],
		category: ["apunte", "pintura"],
		isAvailable: false
	},
	{
		id: "apunte-acrílico-4",
		title: "Apunte Acrílico 4",
		images: [
		{
			name: "main",
			picture: apunte_acr_lico_4
		}
		],
		category: ["apunte", "pintura"],
		isAvailable: false
	},
	{
		id: "apunte-acuarela-paloma",
		title: "Apunte Acuarela Paloma",
		images: [
		{
			name: "main",
			picture: apunte_acuarela_paloma
		}
		],
		category: ["acuarela", "apunte"],
		isAvailable: false
	},
	{
		id: "apunte-baeza-acuerela",
		title: "Apunte Baeza Acuerela",
		images: [
		{
			name: "main",
			picture: apunte_baeza_acuerela
		}
		],
		category: ["apunte", "acuarela"],
		isAvailable: false
	},
	{
		id: "apunte-grafito",
		title: "Apunte Grafito",
		images: [
		{
			name: "main",
			picture: apunte_grafito
		}
		],
		category: ["dibujo", "apunte"],
		isAvailable: false
	},
	{
		id: "apunte-paisaje-acuarela-1",
		title: "Apunte Paisaje Acuarela 1",
		images: [
		{
			name: "main",
			picture: apunte_paisaje_acuarela_1
		}
		],
		category: ["acuarela", "apunte"],
		isAvailable: false
	},
	{
		id: "apunte-paisaje-acuarela-3",
		title: "Apunte Paisaje Acuarela 3",
		images: [
		{
			name: "main",
			picture: apunte_paisaje_acuarela_3
		}
		],
		category: ["acuarela", "apunte"],
		isAvailable: false
	},
	{
		id: "apunte-paisaje-acuarela-4",
		title: "Apunte Paisaje Acuarela 4",
		images: [
		{
			name: "main",
			picture: apunte_paisaje_acuarela_4
		}
		],
		category: ["acuarela", "apunte"],
		isAvailable: false
	},
	{
		id: "apunte-paisaje-acuarela-5",
		title: "Apunte Paisaje Acuarela 5",
		images: [
		{
			name: "main",
			picture: apunte_paisaje_acuarela_5
		}
		],
		category: ["acuarela", "apunte"],
		isAvailable: false
	},
	{
		id: "apunte-paisaje-collage-1",
		title: "Apunte Paisaje Collage 1",
		images: [
		{
			name: "main",
			picture: apunte_paisaje_collage_1
		}
		],
		category: ["apunte", "pintura"],
		isAvailable: false
	},
	{
		id: "apunte-paisaje-collage-2",
		title: "Apunte Paisaje Collage 2",
		images: [
		{
			name: "main",
			picture: apunte_paisaje_collage_2
		}
		],
		category: ["apunte", "pintura"],
		isAvailable: false
	},
	{
		id: "belong",
		title: "Belong",
		images: [
		{
			name: "main",
			picture: belong
		}
		],
		category: "acuarela",
		isAvailable: false
	},
	{
		id: "celebes-sea",
		title: "Celebes Sea",
		images: [
		{
			name: "main",
			picture: celebes_sea
		},
		{
			name: "zoom-1",
			picture: celebes_sea_zoom_1
		},
		{
			name: "zoom-2",
			picture: celebes_sea_zoom_2
		},
		{
			name: "zoom-3",
			picture: celebes_sea_zoom_3
		}
		],
		category: "acuarela",
		isAvailable: false
	},
	{
		id: "dama-acuarela",
		title: "Dama Acuarela",
		images: [
		{
			name: "main",
			picture: dama_acuarela
		},
		{
			name: "zoom-1",
			picture: dama_acuarela_zoom_1
		}
		],
		category: "acuarela",
		isAvailable: false
	},
	{
		id: "dama",
		title: "Dama",
		images: [
		{
			name: "main",
			picture: dama
		}
		],
		category: "dibujo",
		isAvailable: false
	},
	{
		id: "estudio-anatomia",
		title: "Estudio Anatomia",
		images: [
		{
			name: "main",
			picture: estudio_anatomia
		},
		{
			name: "zoom-1",
			picture: estudio_anatomia_zoom_1
		}
		],
		category: ["apunte","dibujo"],
		isAvailable: false
	},
	{
		id: "estudio-retrato-1",
		title: "Estudio Retrato 1",
		images: [
		{
			name: "main",
			picture: estudio_retrato_1
		},
		{
			name: "zoom-1",
			picture: estudio_retrato_1_zoom_1
		},
		{
			name: "zoom-2",
			picture: estudio_retrato_1_zoom_2
		}
		],
		category: ["apunte","acuarela"],
		isAvailable: false
	},
	{
		id: "estudio-retrato-2",
		title: "Estudio Retrato 2",
		images: [
		{
			name: "main",
			picture: estudio_retrato_2
		},
		{
			name: "zoom-1",
			picture: estudio_retrato_2_zoom_1
		},
		{
			name: "zoom-2",
			picture: estudio_retrato_2_zoom_2
		}
		],
		category: ["apunte","acuarela"],
		isAvailable: false
	},
	{
		id: "grafito-catedral",
		title: "Grafito Catedral",
		images: [
		{
			name: "main",
			picture: grafito_catedral
		}
		],
		category: ["dibujo", "apunte"],
		isAvailable: false
	},
	{
		id: "hombre-con-barba",
		title: "Hombre Con Barba",
		images: [
		{
			name: "main",
			picture: hombre_con_barba
		}
		],
		category: "acuarela",
		isAvailable: false
	},
	{
		id: "inherente",
		title: "Inherente",
		images: [
		{
			name: "main",
			picture: inherente
		}
		],
		category: "dibujo",
		isAvailable: false
	},
	{
		id: "lechera",
		title: "Lechera",
		images: [
		{
			name: "main",
			picture: lechera
		}
		],
		category: "pintura",
		isAvailable: false
	},
	{
		id: "notional",
		title: "Notional",
		images: [
		{
			name: "zoom-1",
			picture: notional_zoom_1
		},
		{
			name: "zoom-2",
			picture: notional_zoom_2
		}
		],
		category: "pintura",
		isAvailable: false
	},
	{
		id: "nuevos-acercamientos",
		title: "Nuevos Acercamientos",
		images: [
		{
			name: "main",
			picture: nuevos_acercamientos
		}
		],
		category: "acuarela",
		isAvailable: false
	},
	{
		id: "perpetuidad",
		title: "Perpetuidad",
		images: [
		{
			name: "main",
			picture: perpetuidad
		}
		],
		category: "acuarela",
		isAvailable: false
	},
	{
		id: "provecto",
		title: "Provecto",
		images: [
		{
			name: "main",
			picture: provecto
		},
		{
			name: "zoom-1",
			picture: provecto_zoom_1
		}
		],
		category: "acuarela",
		isAvailable: false
	},
	{
		id: "retrato-del-fayum",
		title: "Retrato Del Fayum",
		images: [
		{
			name: "main",
			picture: retrato_del_fayum
		}
		],
		category: "grabado",
		isAvailable: false
	},
	{
		id: "retrato-sanguina",
		title: "Retrato Sanguina",
		images: [
		{
			name: "main",
			picture: retrato_sanguina
		}
		],
		category: "dibujo",
		isAvailable: false
	},
	{
		id: "summary",
		title: "Summary",
		images: [
		{
			name: "main",
			picture: summary
		}
		],
		category: ["dibujo","pintura"],
		isAvailable: false
	},
	{
		id: "the-joke",
		title: "The Joke",
		images: [
		{
			name: "main",
			picture: the_joke
		}
		],
		category: "pintura",
		isAvailable: false
	},
	{
		id: "the-rockero",
		title: "The Rockero",
		images: [
		{
			name: "main",
			picture: the_rockero
		}
		],
		category: "pintura",
		isAvailable: false
	},
	{
		id: "theophany",
		title: "Theophany",
		images: [
		{
			name: "main",
			picture: theophany
		}
		],
		category: "acuarela",
		isAvailable: false
	},
	{
		id: "time-after-time",
		title: "Time After Time",
		images: [
		{
			name: "main",
			picture: time_after_time
		}
		],
		category: "dibujo",
		isAvailable: false
	},
	{
		id: "tragaluz",
		title: "Tragaluz",
		images: [
		{
			name: "main",
			picture: tragaluz
		}
		],
		category: "pintura",
		isAvailable: false
	},
	{
		id: "vetusto",
		title: "Vetusto",
		images: [
		{
			name: "main",
			picture: vetusto
		},
		{
			name: "zoom-1",
			picture: vetusto_zoom_1
		}
		],
		category: "dibujo",
		isAvailable: false
	},
	{
		id: "xauen",
		title: "Xauen",
		images: [
		{
			name: "main",
			picture: xauen
		}
		],
		category: "acuarela",
		isAvailable: false
	},
	{
		id: "zalema",
		title: "Zalema",
		images: [
		{
			name: "main",
			picture: zalema
		}
		],
		category: "pintura",
		isAvailable: false
	}
];

// Helper functions
export function getArtworkById(id: string): Artwork | undefined {
	return artworkData.find((artwork) => artwork.id === id);
}

export function getArtworksByCategory(category: string): Artwork[] {
	return artworkData.filter((artwork) => {
		if (Array.isArray(artwork.category)) {
			return artwork.category.includes(category);
		}
		return artwork.category === category;
	});
}

export function getAvailableCategories(): string[] {
	const categories = new Set<string>();
	artworkData.forEach((artwork) => {
		if (Array.isArray(artwork.category)) {
			artwork.category.forEach(cat => categories.add(cat));
		} else {
			categories.add(artwork.category);
		}
	});
	return Array.from(categories).sort();
}

export function getRandomArtwork(): Artwork {
	const randomIndex = Math.floor(Math.random() * artworkData.length);
	return artworkData[randomIndex];
}

// Export all imported images for direct access if needed
export const importedImages = {
	albor_zoom_1,
	albor,
	alcon_collage,
	apunte_abstracto_1,
	apunte_abstracto_2,
	apunte_abstracto_3,
	apunte_acrilico_1,
	apunte_acrilico_2,
	apunte_acrilico_3,
	apunte_acr_lico_2_zoom_1,
	apunte_acr_lico_4,
	apunte_acuarela_paloma,
	apunte_baeza_acuerela,
	apunte_grafito,
	apunte_paisaje_acuarela_1,
	apunte_paisaje_acuarela_3,
	apunte_paisaje_acuarela_4,
	apunte_paisaje_acuarela_5,
	apunte_paisaje_collage_1,
	apunte_paisaje_collage_2,
	belong,
	celebes_sea_zoom_1,
	celebes_sea_zoom_2,
	celebes_sea_zoom_3,
	celebes_sea,
	dama_acuarela_zoom_1,
	dama_acuarela,
	dama,
	estudio_anatomia_zoom_1,
	estudio_anatomia,
	estudio_retrato_1_zoom_1,
	estudio_retrato_1_zoom_2,
	estudio_retrato_1,
	estudio_retrato_2_zoom_1,
	estudio_retrato_2_zoom_2,
	estudio_retrato_2,
	grafito_catedral,
	hombre_con_barba,
	inherente,
	lechera,
	notional_zoom_1,
	notional_zoom_2,
	nuevos_acercamientos,
	perpetuidad,
	provecto_zoom_1,
	provecto,
	retrato_del_fayum,
	retrato_sanguina,
	summary,
	the_joke,
	the_rockero,
	theophany,
	time_after_time,
	tragaluz,
	vetusto_zoom_1,
	vetusto,
	xauen,
	zalema
} as const;
